name: CI
 on: [push, pull_request]
 jobs:
   tests:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         include:
           - { os: ubuntu-latest, ruby: 2.7 }
           - { os: ubuntu-latest, ruby: 3.0 }
           - { os: ubuntu-latest, ruby: jruby, allow-failure: true }
           - { os: ubuntu-latest, ruby: jruby-head, allow-failure: true }
           - { os: ubuntu-latest, ruby: head, allow-failure: true }

     steps:
       - uses: actions/checkout@v2
       - name: Set up Ruby
         uses: ruby/setup-ruby@v1
         with:
           ruby-version: ${{ matrix.ruby }}
           bundler-cache: true

       - name: Run tests
         timeout-minutes: 10
         run: bundle exec rake
